### ISSUE TITLE
[Feat] 보관함 메뉴 기능 추가 및 헤더 수정

### ISSUE THREAD

**Issue by JMM00** [Gwamegis/Moya#122]
### Issue
- 응원가 리스트에서 메뉴 버튼 클릭 시 나타나는 bottom sheet 구현
- 헤더 스크롤 조건 추가 (헤더가 스크롤 중간에 멈추는 현상 방지)

### Todo
- 필요한 작업들을 세분화해서 적어주세요.
- [ ] bottom sheet (half sheet) 구현
- [ ] 데이터 전달 및 기능 추가
- [ ] 헤더 스크롤 가능 조건 추가

### Due Date
- 23년 6월 23일 금요일
